### ISSUE TITLE
Bug: using absolute paths throws FileExistsError

### ISSUE THREAD

**Issue by lukaw3d** [mschuett/yaml-shellcheck#12]
```sh
$ docker run -v `pwd`:/app2 --rm quay.io/mschuette/yaml-shellcheck /app2/test-input/github-workflow.yml

2024-08-14 02:18:05,957 - root - INFO - read /app2/test-input/github-workflow.yml as GitHub Actions config...
Traceback (most recent call last):
  File "/app/yaml_shellcheck.py", line 459, in <module>
    main()
  File "/app/yaml_shellcheck.py", line 448, in main
    filenames.extend(write_tmp_files(args, result))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/yaml_shellcheck.py", line 402, in write_tmp_files
    subdir.mkdir(exist_ok=True, parents=True)
  File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/app2/test-input/github-workflow.yml'
```

or

```sh
$ docker run -v `pwd`:`pwd` --rm quay.io/mschuette/yaml-shellcheck  `pwd`/**/*.y*ml
2024-08-14 02:32:29,902 - root - INFO - read /home/luka/Downloads/yaml-shellcheck/test-input/ansible-playbook.yml as Ansible file...
Traceback (most recent call last):
  File "/app/yaml_shellcheck.py", line 459, in <module>
    main()
  File "/app/yaml_shellcheck.py", line 448, in main
    filenames.extend(write_tmp_files(args, result))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/yaml_shellcheck.py", line 402, in write_tmp_files
    subdir.mkdir(exist_ok=True, parents=True)
  File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/home/luka/Downloads/yaml-shellcheck/test-input/ansible-playbook.yml'
```

This happens because https://github.com/mschuett/yaml-shellcheck/blob/2608670944fe48bf08e2bd334cf4114db8c6b4d3/yaml_shellcheck.py#L397

is just `subdir = filename` for absolute paths.

### Naive fix

https://github.com/lukaw3d/yaml-shellcheck/commit/8df5d6476862712fbb3afcd31288348a55e9f6b0

```sh
$ docker run -v `pwd`:/app2 --rm ghcr.io/lukaw3d/yaml-shellcheck:main /app2/test-input/github-workflow.yml
2024-08-14 02:29:29,192 - root - INFO - read /app2/test-input/github-workflow.yml as GitHub Actions config...

In a/app2/test-input/github-workflow.yml/jobs/hello_world_job/steps/2/run line 2:
echo random-number $ACTION_EXPRESSION
                   ^----------------^ SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean: 
echo random-number "$ACTION_EXPRESSION"

For more information:
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
```

**Comment by mschuett** [comment]
fixed in the PR and released as part of [v1.4.0](https://github.com/mschuett/yaml-shellcheck/releases/tag/v1.4.0)
